"""initial migration

Revision ID: 0d6a833b7968
Revises: 
Create Date: 2026-01-15 18:13:30.412576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d6a833b7968'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('severity', sa.Enum('SEV1', 'SEV2', 'SEV3', 'SEV4', name='severity'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'MITIGATED', 'RESOLVED', name='status'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(title)) > 0', name='title_not_empty'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incidents_created_at', 'incidents', [sa.text('created_at DESC')], unique=False)
    op.create_index('ix_incidents_status_created_at', 'incidents', ['status', 'created_at'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.BigInteger(), nullable=False),
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.CheckConstraint('length(trim(event_type)) > 0', name='event_type_not_empty'),
    sa.CheckConstraint('length(trim(message)) > 0', name='message_not_empty'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_timeline_incident_occurred', 'timeline_events', ['incident_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_timeline_incident_occurred', table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index('ix_incidents_status_created_at', table_name='incidents')
    op.drop_index('ix_incidents_created_at', table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
