"""add created_at and updated_at timestamps to timeline events

Revision ID: 941cca91d37c
Revises: a2746ead8fc0
Create Date: 2026-01-23 15:56:06.080615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '941cca91d37c'
down_revision: Union[str, Sequence[str], None] = 'a2746ead8fc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timeline_events', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('timeline_events', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timeline_events', 'updated_at')
    op.drop_column('timeline_events', 'created_at')
    # ### end Alembic commands ###
