from __future__ import annotations
from typing import Protocol

from backend.domain.incidents.entities import Incident, TimelineEvent
from backend.domain.incidents.enums import Severity, Status


class IncidentRepository(Protocol):
    def list(self, *, status: Status | None = None, severity: Severity | None = None) -> list[Incident]: ...
    def get(self, incident_id: int) -> Incident | None: ...
    def get_with_events(self, incident_id: int) -> Incident | None: ...
    def create(self, incident_data: dict) -> Incident: ...
    def update(self, incident_id: int, changes: dict) -> Incident | None: ...
    def delete(self, incident_id: int) -> bool: ...


class TimelineEventRepository(Protocol):
    def list_incident_events(self, incident_id: int) -> list[TimelineEvent]: ...
    def get(self, incident_id: int, event_id: int) -> TimelineEvent | None: ...
    def create(self, incident_id: int, event_data: dict) -> TimelineEvent: ...
    def update(self, incident_id: int, event_id: int, changes: dict) -> TimelineEvent | None: ...
    def delete(self, incident_id: int, event_id: int) -> bool: ...


class UnitOfWork(Protocol):
    incidents: IncidentRepository
    events: TimelineEventRepository

    def commit(self) -> None: ...
    def rollback(self) -> None: ...

    def __enter__(self) -> "UnitOfWork": ...
    def __exit__(self, exc_type, exc, tb) -> None: ...
